const fs = require('fs');

const SUPABASE_URL = process.env.SUPABASE_URL || 'YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

const config = `// ===== SUPABASE CONFIGURATION =====
// Auto-generated by build.js from environment variables
const SUPABASE_URL = '${SUPABASE_URL}';
const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';

// Initialize Supabase client (loaded from CDN in index.html)
window.supabaseClient = null;

function initSupabase() {
  if (typeof supabase !== 'undefined' && supabase.createClient) {
    window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    return window.supabaseClient;
  }
  console.error('Supabase SDK not loaded');
  return null;
}
`;

fs.writeFileSync('./js/supabase-config.js', config);
console.log('Supabase config generated successfully');
console.log(`  URL: ${SUPABASE_URL === 'YOUR_SUPABASE_URL' ? '(not set)' : SUPABASE_URL}`);
console.log(`  Key: ${SUPABASE_ANON_KEY === 'YOUR_SUPABASE_ANON_KEY' ? '(not set)' : '****' + SUPABASE_ANON_KEY.slice(-8)}`);
